services:
  - type: web
    name: tourism-analytics-platform
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
    autoDeploy: true
    healthCheckPath: /