"""Initial migration

Revision ID: 396dd435285a
Revises: 
Create Date: 2025-06-22 23:43:50.029505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396dd435285a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('issue_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_feedback_id'), 'chat_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_chat_feedback_session_id'), 'chat_feedback', ['session_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('original_language', sa.String(), nullable=True),
    sa.Column('translated_content', sa.Text(), nullable=True),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('entities', sa.Text(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('user_location', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_business_id'), 'chat_sessions', ['business_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_session_id'), 'chat_sessions', ['session_id'], unique=True)
    op.create_table('forecast_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('predicted_visitors', sa.Float(), nullable=False),
    sa.Column('predicted_revenue', sa.Float(), nullable=True),
    sa.Column('predicted_bookings', sa.Float(), nullable=True),
    sa.Column('confidence_interval_lower', sa.Float(), nullable=True),
    sa.Column('confidence_interval_upper', sa.Float(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_results_business_id'), 'forecast_results', ['business_id'], unique=False)
    op.create_index(op.f('ix_forecast_results_forecast_date'), 'forecast_results', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_forecast_results_id'), 'forecast_results', ['id'], unique=False)
    op.create_table('hubspot_sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_type', sa.String(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('hubspot_id', sa.String(), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=False),
    sa.Column('sync_direction', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hubspot_sync_logs_id'), 'hubspot_sync_logs', ['id'], unique=False)
    op.create_table('lead_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('hubspot_activity_id', sa.String(), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activity_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_activities_hubspot_activity_id'), 'lead_activities', ['hubspot_activity_id'], unique=True)
    op.create_index(op.f('ix_lead_activities_id'), 'lead_activities', ['id'], unique=False)
    op.create_index(op.f('ix_lead_activities_lead_id'), 'lead_activities', ['lead_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hubspot_contact_id', sa.String(), nullable=True),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('lead_source', sa.String(), nullable=True),
    sa.Column('lead_status', sa.String(), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=True),
    sa.Column('interest_level', sa.String(), nullable=True),
    sa.Column('travel_dates', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('party_size', sa.Integer(), nullable=True),
    sa.Column('budget_range', sa.String(), nullable=True),
    sa.Column('service_interests', sa.JSON(), nullable=True),
    sa.Column('last_contact_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_follow_up', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('converted', sa.Boolean(), nullable=True),
    sa.Column('conversion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conversion_value', sa.Float(), nullable=True),
    sa.Column('synced_to_hubspot', sa.Boolean(), nullable=True),
    sa.Column('last_hubspot_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hubspot_sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_business_id'), 'leads', ['business_id'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=True)
    op.create_index(op.f('ix_leads_hubspot_contact_id'), 'leads', ['hubspot_contact_id'], unique=True)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('reviewer_name', sa.String(), nullable=True),
    sa.Column('reviewer_email', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(), nullable=True),
    sa.Column('emotions', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_business_id'), 'reviews', ['business_id'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_table('tourism_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('visitor_count', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('bookings', sa.Integer(), nullable=False),
    sa.Column('cancellations', sa.Integer(), nullable=False),
    sa.Column('occupancy_rate', sa.Float(), nullable=True),
    sa.Column('average_stay_duration', sa.Float(), nullable=True),
    sa.Column('source_market', sa.String(), nullable=True),
    sa.Column('weather_condition', sa.String(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('is_holiday', sa.Boolean(), nullable=True),
    sa.Column('is_weekend', sa.Boolean(), nullable=True),
    sa.Column('special_event', sa.String(), nullable=True),
    sa.Column('marketing_spend', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tourism_data_business_id'), 'tourism_data', ['business_id'], unique=False)
    op.create_index(op.f('ix_tourism_data_date'), 'tourism_data', ['date'], unique=False)
    op.create_index(op.f('ix_tourism_data_id'), 'tourism_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tourism_data_id'), table_name='tourism_data')
    op.drop_index(op.f('ix_tourism_data_date'), table_name='tourism_data')
    op.drop_index(op.f('ix_tourism_data_business_id'), table_name='tourism_data')
    op.drop_table('tourism_data')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_business_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_hubspot_contact_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_business_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_lead_activities_lead_id'), table_name='lead_activities')
    op.drop_index(op.f('ix_lead_activities_id'), table_name='lead_activities')
    op.drop_index(op.f('ix_lead_activities_hubspot_activity_id'), table_name='lead_activities')
    op.drop_table('lead_activities')
    op.drop_index(op.f('ix_hubspot_sync_logs_id'), table_name='hubspot_sync_logs')
    op.drop_table('hubspot_sync_logs')
    op.drop_index(op.f('ix_forecast_results_id'), table_name='forecast_results')
    op.drop_index(op.f('ix_forecast_results_forecast_date'), table_name='forecast_results')
    op.drop_index(op.f('ix_forecast_results_business_id'), table_name='forecast_results')
    op.drop_table('forecast_results')
    op.drop_index(op.f('ix_chat_sessions_session_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_business_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_feedback_session_id'), table_name='chat_feedback')
    op.drop_index(op.f('ix_chat_feedback_id'), table_name='chat_feedback')
    op.drop_table('chat_feedback')
    # ### end Alembic commands ###